### ISSUE TITLE
Keep the name "Dota 2 Redux"

### ISSUE THREAD

**Issue by SwordBacon** [darklordabc/Dota-2-Redux#557]
Just talked with Baumi and his crew. The consensus is that renaming to "Legends of Dota: FIXED" is a dick move and he will NEVER do a video of the mod if it doesn't change. 

I agree with him.

**Comment by Wouterz90** [comment]
Me too, Ash also does not deserve this.

**Comment by SwordBacon** [comment]
I think we've had enough discussion on Discord about this issue, so I'll close it.
